import type { AIModel } from '@/types/index';

// TokenDance 模型注册表 — 基于 https://tokendance.space/gateway/v1/models 真实列表
// 共 48 个模型，分为图片、视频、对话三类
export const MODEL_REGISTRY: AIModel[] = [
  // ── 图片生成模型 ──────────────────────────────────────────
  {
    id: 'seedream-5.0-lite',
    name: 'Seedream 5.0 Lite',
    provider: 'ByteDance Seed',
    type: 'image',
    description: '字节 Seedream 5.0 轻量版文生图，支持 ark/openai 双协议',
    isAsync: false,
  },
  {
    id: 'ernie-image',
    name: 'ERNIE Image',
    provider: 'Baidu',
    type: 'image',
    description: '百度文心图像生成，OpenAI 兼容协议',
    isAsync: false,
  },

  // ── 视频生成模型 ──────────────────────────────────────────
  {
    id: 'seedance-2.0',
    name: 'Seedance 2.0',
    provider: 'ByteDance',
    type: 'video',
    description: '字节 Seedance 2.0 高质量文生/图生视频',
    isAsync: true,
  },
  {
    id: 'seedance-2.0-fast',
    name: 'Seedance 2.0 Fast',
    provider: 'ByteDance',
    type: 'video',
    description: '字节 Seedance 2.0 快速版，生成速度更快',
    isAsync: true,
  },
  {
    id: 'happyhorse-1.0-t2v',
    name: 'HappyHorse 1.0 T2V',
    provider: 'Alibaba',
    type: 'video',
    description: '阿里 HappyHorse 文生视频',
    isAsync: true,
  },
  {
    id: 'happyhorse-1.0-i2v',
    name: 'HappyHorse 1.0 I2V',
    provider: 'Alibaba',
    type: 'video',
    description: '阿里 HappyHorse 图生视频',
    isAsync: true,
  },
  {
    id: 'happyhorse-1.0-r2v',
    name: 'HappyHorse 1.0 R2V',
    provider: 'Alibaba',
    type: 'video',
    description: '阿里 HappyHorse 参考生视频',
    isAsync: true,
  },
  {
    id: 'happyhorse-1.0-video-edit',
    name: 'HappyHorse 1.0 Edit',
    provider: 'Alibaba',
    type: 'video',
    description: '阿里 HappyHorse 视频编辑',
    isAsync: true,
  },

  // ── 对话模型 ──────────────────────────────────────────────
  {
    id: 'minimax-m2.7',
    name: 'MiniMax M2.7',
    provider: 'MiniMax',
    type: 'chat',
    description: '面向自主执行与生产力场景的下一代大模型，200K 上下文',
    isAsync: false,
  },
  {
    id: 'minimax-m2.5',
    name: 'MiniMax M2.5',
    provider: 'MiniMax',
    type: 'chat',
    description: 'MiniMax 专为真实工作场景打造的大语言模型，200K 上下文',
    isAsync: false,
  },
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    provider: 'DeepSeek',
    type: 'chat',
    description: 'DeepSeek 最新旗舰模型，1M 超长上下文',
    isAsync: false,
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    provider: 'DeepSeek',
    type: 'chat',
    description: 'DeepSeek V4 快速版，1M 上下文',
    isAsync: false,
  },
  {
    id: 'deepseek-v3.2',
    name: 'DeepSeek V3.2',
    provider: 'DeepSeek',
    type: 'chat',
    description: 'DeepSeek V3.2 算力效率与强推理兼顾，128K 上下文',
    isAsync: false,
  },
  {
    id: 'deepseek-chat-v3-0324',
    name: 'DeepSeek V3 0324',
    provider: 'DeepSeek',
    type: 'chat',
    description: 'DeepSeek Chat V3 2024-03-24 版本，128K 上下文',
    isAsync: false,
  },
  {
    id: 'qwen3.7-max',
    name: 'Qwen3.7 Max',
    provider: 'Qwen',
    type: 'chat',
    description: 'Qwen3.7 旗舰模型，1M 上下文',
    isAsync: false,
  },
  {
    id: 'qwen3-max',
    name: 'Qwen3 Max',
    provider: 'Qwen',
    type: 'chat',
    description: 'Qwen3 旗舰级对话模型，256K 上下文',
    isAsync: false,
  },
  {
    id: 'qwen3.6-max-preview',
    name: 'Qwen3.6 Max Preview',
    provider: 'Qwen',
    type: 'chat',
    description: 'Qwen3.6 Max 预览版，262K 上下文',
    isAsync: false,
  },
  {
    id: 'qwen3.6-plus',
    name: 'Qwen3.6 Plus',
    provider: 'Qwen',
    type: 'chat',
    description: 'Qwen3.6 Plus，1M 上下文',
    isAsync: false,
  },
  {
    id: 'qwen3.5-plus',
    name: 'Qwen3.5 Plus',
    provider: 'Qwen',
    type: 'chat',
    description: 'Qwen3.5 Plus，1M 上下文',
    isAsync: false,
  },
  {
    id: 'qwen3.5-flash',
    name: 'Qwen3.5 Flash',
    provider: 'Qwen',
    type: 'chat',
    description: 'Qwen3.5 轻量快速版，1M 上下文',
    isAsync: false,
  },
  {
    id: 'qwen3-vl-plus',
    name: 'Qwen3 VL Plus',
    provider: 'Qwen',
    type: 'chat',
    description: 'Qwen3 多模态视觉语言模型，256K 上下文',
    isAsync: false,
  },
  {
    id: 'qwen3-8b',
    name: 'Qwen3 8B',
    provider: 'Qwen',
    type: 'chat',
    description: 'Qwen3 8B 轻量本地级模型，40K 上下文',
    isAsync: false,
  },
  {
    id: 'kimi-k2.6',
    name: 'Kimi K2.6',
    provider: 'MoonshotAI',
    type: 'chat',
    description: 'Moonshot Kimi K2.6，262K 超长上下文',
    isAsync: false,
  },
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5',
    provider: 'MoonshotAI',
    type: 'chat',
    description: 'Moonshot Kimi K2.5，256K 上下文',
    isAsync: false,
  },
  {
    id: 'glm-5.1',
    name: 'GLM 5.1',
    provider: 'Z.ai',
    type: 'chat',
    description: 'Z.ai GLM 5.1，202K 上下文',
    isAsync: false,
  },
  {
    id: 'glm-5',
    name: 'GLM 5',
    provider: 'Z.ai',
    type: 'chat',
    description: 'Z.ai GLM 5 旗舰版，200K 上下文',
    isAsync: false,
  },
  {
    id: 'glm-4.7',
    name: 'GLM 4.7',
    provider: 'Z.ai',
    type: 'chat',
    description: 'Z.ai GLM 4.7，200K 上下文',
    isAsync: false,
  },
  {
    id: 'glm-4.5-air',
    name: 'GLM 4.5 Air',
    provider: 'Z.ai',
    type: 'chat',
    description: 'Z.ai GLM 4.5 轻量版，128K 上下文',
    isAsync: false,
  },
  {
    id: 'glm-4.6v',
    name: 'GLM 4.6V',
    provider: 'Z.ai',
    type: 'chat',
    description: 'Z.ai GLM 4.6 视觉版，128K 上下文',
    isAsync: false,
  },
  {
    id: 'glm-5v-turbo',
    name: 'GLM 5V Turbo',
    provider: 'Z.ai',
    type: 'chat',
    description: 'Z.ai GLM 5V Turbo 视觉加速版，202K 上下文',
    isAsync: false,
  },
  {
    id: 'seed-2.0-pro',
    name: 'Seed-2.0-Pro',
    provider: 'ByteDance Seed',
    type: 'chat',
    description: '字节 Seed 2.0 专业版，256K 上下文',
    isAsync: false,
  },
  {
    id: 'seed-2.0-lite',
    name: 'Seed-2.0-Lite',
    provider: 'ByteDance Seed',
    type: 'chat',
    description: '字节 Seed 2.0 轻量版，256K 上下文',
    isAsync: false,
  },
  {
    id: 'seed-2.0-mini',
    name: 'Seed-2.0-Mini',
    provider: 'ByteDance Seed',
    type: 'chat',
    description: '字节 Seed 2.0 迷你版，256K 上下文',
    isAsync: false,
  },
  {
    id: 'step-3.5-flash',
    name: 'Step 3.5 Flash',
    provider: 'StepFun',
    type: 'chat',
    description: '阶跃星辰 Step 3.5 快速版，256K 上下文',
    isAsync: false,
  },
  {
    id: 'mimo-v2.5-pro',
    name: 'MiMo-V2.5-Pro',
    provider: 'Xiaomi',
    type: 'chat',
    description: '小米 MiMo V2.5 专业版，1M 上下文',
    isAsync: false,
  },
  {
    id: 'mimo-v2.5',
    name: 'MiMo-V2.5',
    provider: 'Xiaomi',
    type: 'chat',
    description: '小米 MiMo V2.5，1M 上下文',
    isAsync: false,
  },
  {
    id: 'mimo-v2-pro',
    name: 'MiMo-V2-Pro',
    provider: 'Xiaomi',
    type: 'chat',
    description: '小米 MiMo V2 专业版，256K 上下文',
    isAsync: false,
  },
  {
    id: 'mimo-v2-omni',
    name: 'MiMo-V2-Omni',
    provider: 'Xiaomi',
    type: 'chat',
    description: '小米 MiMo V2 全能版，262K 上下文',
    isAsync: false,
  },
  {
    id: 'unifuncs-s3',
    name: 'UniFuncs Deep Search S3',
    provider: 'UniFuncs',
    type: 'chat',
    description: 'UniFuncs 深度搜索 S3，200K 上下文',
    isAsync: false,
  },
  {
    id: 'unifuncs-u3',
    name: 'UniFuncs Deep Research U3',
    provider: 'UniFuncs',
    type: 'chat',
    description: 'UniFuncs 深度研究 U3，200K 上下文',
    isAsync: false,
  },
  {
    id: 'deepseek-ocr-2',
    name: 'DeepSeek OCR 2',
    provider: 'DeepSeek',
    type: 'chat',
    description: 'DeepSeek OCR 2 文档识别专用，8K 上下文',
    isAsync: false,
  },
  {
    id: 'qianfan-ipcharacter',
    name: 'Qianfan IPCharacter',
    provider: 'Baidu',
    type: 'chat',
    description: '百度千帆 IP 角色扮演模型，16K 上下文',
    isAsync: false,
  },
  {
    id: 'mimo-v2.5-tts',
    name: 'MiMo-V2.5-TTS',
    provider: 'Xiaomi',
    type: 'chat',
    description: '小米 MiMo 文字转语音，8K 上下文',
    isAsync: false,
  },
  {
    id: 'mimo-v2.5-tts-voicedesign',
    name: 'MiMo-V2.5-TTS-VoiceDesign',
    provider: 'Xiaomi',
    type: 'chat',
    description: '小米 MiMo TTS 音色设计版，8K 上下文',
    isAsync: false,
  },
  {
    id: 'mimo-v2.5-tts-voiceclone',
    name: 'MiMo-V2.5-TTS-VoiceClone',
    provider: 'Xiaomi',
    type: 'chat',
    description: '小米 MiMo TTS 音色克隆版，8K 上下文',
    isAsync: false,
  },
];

export const IMAGE_MODELS = MODEL_REGISTRY.filter(m => m.type === 'image');
export const VIDEO_MODELS = MODEL_REGISTRY.filter(m => m.type === 'video');
export const CHAT_MODELS = MODEL_REGISTRY.filter(m => m.type === 'chat');

// 默认模型（均使用真实 API ID）
export const DEFAULT_IMAGE_MODEL = 'seedream-5.0-lite';
export const DEFAULT_VIDEO_MODEL = 'seedance-2.0';
export const DEFAULT_CHAT_MODEL = 'deepseek-v3.2';

export function getModel(id: string): AIModel | undefined {
  return MODEL_REGISTRY.find(m => m.id === id);
}

